# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1(self):
    self.driver.get("https://test.sugaringfactory.com/index.php?route=account%2Fregister")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.NAME, "firstname").click()
    self.driver.find_element(By.NAME, "firstname").click()
    self.driver.find_element(By.NAME, "firstname").click()
    self.driver.find_element(By.NAME, "firstname").send_keys("kkkkk")
    self.driver.find_element(By.NAME, "lastname").click()
    self.driver.find_element(By.NAME, "lastname").send_keys("kkkkkk")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("kkkkkkk")
    self.driver.find_element(By.NAME, "telephone").click()
    self.driver.find_element(By.NAME, "telephone").send_keys("5555555555")
    self.driver.find_element(By.NAME, "address_1").click()
    self.driver.find_element(By.NAME, "address_1").send_keys("7 hjkkk")
    self.driver.find_element(By.NAME, "city").click()
    self.driver.find_element(By.NAME, "city").send_keys("gggggg")
    self.driver.find_element(By.NAME, "postcode").click()
    self.driver.find_element(By.NAME, "postcode").send_keys("444444")
    self.driver.find_element(By.NAME, "zone_id").click()
    dropdown = self.driver.find_element(By.NAME, "zone_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Indiana']").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("77777777")
    self.driver.find_element(By.NAME, "confirm").click()
    self.driver.find_element(By.NAME, "confirm").send_keys("77777777")
    self.driver.find_element(By.NAME, "newsletter").click()
    self.driver.find_element(By.NAME, "captcha").click()
    self.driver.find_element(By.NAME, "captcha").send_keys("513ee8")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".center span")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".center span").click()
  
